# Poisson Regression

## What is Poisson data?

Poisson data occurs when there is a need to model counts. The counts of events being modeled should be independent and the upper limit of the counts is much greater than the majority of the counts or even may not exist. Possion GLMs can also be used to model rates, used to compare counts across the unit of populations, when a Binomial GLM would not be appropriate. This occurs when populations are large and the rate of occurance is very small, usually less than 1%. The Poisson distribution has probability function P(y|$\mu$) = $e^{-\mu}\mu^y/y!$ for y = 0, 1, 2,... and $\mu$ > 0.

## Why ordinary least squares does not work for Poisson data

Ordinary least squares (OLS) regression cannot be used for Poisson data. Count data violates the constant variance assumption of OLS because as the counts are smaller and approach 0, the variance of the response must decrease, and as the counts grow larger, the variance of the response will tend to increase. The normal distribution is also not adequate for modeling the random component of count data because counts are both non-negative and discrete. The Poisson distribution is a more suitable option to model count data.

## Link functions for Poisson GLM's

The most common link function used for Poisson regression is the logrithmic link function because it guarentees that $\mu$ will be greater than 0 and makes interpretation of the regression parameters more straightforward, since they are interpreted as having multiplicative effects. The systematic component of a Poisson GLM is $\mu = e^{\beta_0 + \beta_1x_1 + ... + \beta_px_p}$ and increasing $x_j$ by one will increase $\mu$ by a factor of $\beta_j$. Other link functions, while less commmon, can be used for a Poisson GLM. The identity link function, where $\eta = \mu$, or the sqrt link function, where $\eta = \sqrt{\mu}$, are two options. When all of the explanatory variables are quantitative, the data are modeled by a Poisson regression model. Additionally, quantile residuals should be used to asses the model fit since the data are discrete. Count data can also be represented in contingency tables so that observations can be cross-classified in their relevant categories. These data are modeled using a log-linear model, where all of the explanatory variables are qualitative.

## Problems of overdispersion and solutions

A characteristic of the Poisson distribution is that the mean $\mu$ equals the variance. However, when modeling real data, this assumption can be a bit ${fishy}$, since the variance is usually greater than $\mu$, which is overdispersion. Overdispersion occurs because the events being counted have a positive correlation and so are not independent. Overdispersion is an issue in Poisson GLM's because the standard errors of the estimated $\beta_j$ will be underestimated, making the model's explanatory variables appear more significant than they actually are. Models fit using the Poisson family can be checked for overdispersion by comparing the residual deviance compared to the residual degrees of freedom. If the residual deviance is greater than the degrees of freedom, the model is overdispersed, and if the residual deviance is much less than the degrees of freedom, the model is underdispersed, a less frequent occurence. A large residual deviance compared to the residual degrees of freedom could also indicate a lack of fit, but this can be checked by eliminating outliers and fits the a model with the most explanatory variables possible. The residual deviance will still be large if overdispersion is the issue. Similarly, the Pearson goodness-of-fit statistic can be compared to the residual degrees of freedom to check for overdispersion. This method should be used when the counts are small, so asymptotic approximations would not be appropriate. Here, large goodness-of-fit statistics indicate a poor fit. If there is overdispersion after fitting a Poisson GLM, the model can be fit using other related families. By modeling the data using a hierarchical model to add more variability, $\mu$ can be treated as a random variable, resulting in the response variable of interest following a negative binomial distribution. The expectation of $y_i$ is $\mu_i$ and the variance of $y_i$ is now $\mu_i + \psi\mu_i^2$, where $\psi\mu_i^2$ is the added overdispersion term and $\psi$ is larger when overdispersion is greater. The MASS package contains the function glm.nb() to model negative binomial GLMs. The standard link function is the log-link function so that $\mu$ > 0, and similar to the Poisson GLM, quantile residuals should be used. Quasi-Poisson models are another alternative to Poisson GLMs when there is overdispersion. The variance of $y_i$ is now $\phi\mu_i$, where $\phi$ > 1 represents overdispersion and raises standard errors to a factor of $\sqrt{\phi}$. Quasi-Poisson models can be fit in R by family = quasipoisson(). Quantile residuals cannot be found because the quasi-Poisson model is not a probability model but standardized deviance residuals can be examoned.
