---
title: "Tutorial"
output: learnr::tutorial
runtime: shiny_prerendered
resource_files:
- GRM_LearnR_files/figure-html/unnamed-chunk-1-1.png
- GRM_LearnR.Rmd
- GRM_LearnR.html
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE)
```


## Example case where Linear models fail 

```{r, echo = F}
data <- read_csv("https://raw.githubusercontent.com/empalmer/GRMA/main/learnR_data/data_ex1.csv")

ggplot(data)+ 
  geom_point(aes(x,y))
```


```{r quiz}
quiz(
  question("Why is a linear model not appropriate here?",
    answer("Non-normal errors", correct = TRUE),
    answer("Line should be constratined between 0 and 1", correct = TRUE)
  )
)
```




### Code:

Which family should we specify in `glm()`

```{r quiz2}
quiz(
  question("Which family should we specify in glm()",
    answer("binomial", correct = TRUE),
    answer("gaussian"),
    answer("poisson")
  )
)
```


Write the R code required to run a generalized linear model using the given `data` data frame. 

```{r glm_call, exercise=TRUE, exercise.eval = TRUE}
data <- read_csv("https://raw.githubusercontent.com/empalmer/GRMA/main/learnR_data/data_ex1.csv")
```

```{r glm_call-hint}
glm(formula, family = , data)
```


### Inference 

What is our estimate for $\hat\beta_1$?

```{r infer}
quiz(
  question("What is our estimate for beta1?",
    answer("-0.01862"),
    answer("3.42975 " , correct = TRUE),
    answer("22.96")
  )
)
```



